[package]
name = "tinydnsproxy"
version = "0.1.0"
authors = ["Stevie Holdway <stevie.holdway@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2"
byteorder = "1.3.2"
lazy_static = "1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.5"
rand = "0.7.2"
regex = "1"

[dev-dependencies]
tempfile = "3.1.0"
